### ISSUE TITLE
Analyses does not complete on example data

### ISSUE THREAD

**Issue by DominikGlodzik** [hartwigmedical/platinum#25]
Hi there,

thank you for putting together this excellent package.

I tried running platinum two times on the example data, as described in the the README. Each time, the analysis fails at the Amber stage. 

Please could you help me understand the problem and potentially fix it?
I attach:
screenshot from `platinum status` that shows the job exit status
screenshot from Google Cloud log explorer, which shows 'Quota_Exceeded'
example of Amber error I found in the result bucket

I run Platinum in a brand new project. This is a Google Cloud trial, so I cannot control the quotas, but on this example no resources come close the the quotas.

Could you please help me understand and potentially fix the problem?
Best
Dominik

![Screen Shot 2021-10-06 at 8 28 20 AM](https://user-images.githubusercontent.com/23527069/136202692-5185ef4c-be1a-4976-a9f8-9f619e35dd3c.png)
![Screen Shot 2021-10-06 at 8 24 40 AM](https://user-images.githubusercontent.com/23527069/136202722-a3331402-9595-4192-8105-f076e7bdf9de.png)

[amber_run (1).log](https://github.com/hartwigmedical/platinum/files/7293715/amber_run.1.log)

**Comment by pauldwolfe** [comment]
Hey @DominikGlodzik sorry for the slow reply, first time anyone has raised an issue. Full disclosure this package is still fairly immature but we do have a few external users using it and providing feedback, we're a small team but hope to find some time to polish this more in the near future.

If you are still interested, happy to work with you to resolve this quota issue. The first step would be to run the example again, and then navigate to the https://console.cloud.google.com/iam-admin/quotas which will show you what quota is being exceeded and the value. Many of the default quotas are quite low (i think only 24 cpus for compute engine) and can be raised via the console.

**Comment by DominikGlodzik** [comment]
Thank you for getting back to me!

I will give it a go and check what quota is being exceeded.

Happy New Year
